import type { MonitorHealth } from "@/health/model";
const checkedAt = "2026-09-03T08:52:13.000Z";
export const mockMonitors: MonitorHealth[] = [
  { id:"metno", name:"MET Norway Weather", status:"ok", checkedAt, dataTime:"2026-09-03T08:00:00.000Z", lastSuccess:checkedAt, ageSeconds:3133, latencyMs:432, httpStatus:200, networkOk:true, parseOk:true, schemaOk:true, fresh:true, recordCount:4, details:{ locations:4, temperatureC:8, windMps:6.4, lowCloudPercent:42, mediumCloudPercent:21, highCloudPercent:9 } },
  { id:"irca", name:"IRCA Roads", status:"error", checkedAt, dataTime:"2026-09-03T07:31:00.000Z", lastSuccess:"2026-09-03T07:31:00.000Z", ageSeconds:4873, latencyMs:195, httpStatus:200, networkOk:true, parseOk:true, schemaOk:true, fresh:false, recordCount:0, errorType:"EMPTY_DATA", errorMessage:"Public endpoint is reachable, but the road dataset contains zero records.", details:{ roads:0, events:0, stations:0 } },
  { id:"noaa-kp", name:"NOAA Kp", status:"error", checkedAt, lastSuccess:"2026-09-03T06:00:00.000Z", latencyMs:276, httpStatus:200, networkOk:true, parseOk:true, schemaOk:false, errorType:"SCHEMA_ERROR", errorMessage:"Required numeric Kp field is missing from the response." },
  { id:"solar-wind", name:"NOAA Solar Wind", status:"ok", checkedAt, dataTime:"2026-09-03T08:47:00.000Z", lastSuccess:checkedAt, ageSeconds:313, latencyMs:218, httpStatus:200, networkOk:true, parseOk:true, schemaOk:true, fresh:true, recordCount:1, details:{ speedKms:514, btNt:6.8, bzNt:-3.1 } },
  { id:"ovation", name:"NOAA OVATION", status:"degraded", checkedAt, dataTime:"2026-09-03T08:00:00.000Z", lastSuccess:checkedAt, ageSeconds:3133, latencyMs:361, httpStatus:200, networkOk:true, parseOk:true, schemaOk:true, fresh:true, recordCount:29, errorType:"HTTP_ERROR", errorMessage:"29 coordinate records loaded; 3 forecast regions are unavailable.", details:{ successfulRegions:29, failedRegions:3 } },
  { id:"ecmwf", name:"ECMWF Cloud Forecast", status:"stale", checkedAt, dataTime:"2026-09-02T15:00:00.000Z", lastSuccess:checkedAt, ageSeconds:64633, latencyMs:144, httpStatus:200, networkOk:true, parseOk:true, schemaOk:true, fresh:false, recordCount:17, errorType:"STALE_DATA", errorMessage:"Manifest is reachable, but the model run is older than the configured threshold.", details:{ modelRun:"2026-09-02T12:00:00.000Z", frameCount:17 } },
  { id:"imo", name:"IMO Warnings", status:"info", checkedAt, dataTime:"2026-09-03T08:45:00.000Z", lastSuccess:checkedAt, ageSeconds:433, latencyMs:173, httpStatus:200, networkOk:true, parseOk:true, schemaOk:true, fresh:true, recordCount:0, details:{ activeWarnings:0, note:"No active warnings." } },
];
export function getMockMonitors() { return mockMonitors; }
